name: Publish

on:
  release:
    types: [created]

permissions:
  contents: read
  id-token: write  # Required for OIDC

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Build Tools and Git
        run: |
          sudo apt-get update
          sudo apt-get install -y git
          python -m pip install --upgrade pip
          pip install build

      - name: Update Version in setup.py and __init__.py
        run: |
          VERSION=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
          sed -i "s/version=.*/version='$VERSION',/" setup.py
          sed -i "s/__version__ = .*/__version__ = '$VERSION'/" lazypredict/__init__.py

      - name: Build Package
        run: python -m build

      - name: Publish to PyPI
        if: github.event.release.prerelease == false
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: 'https://upload.pypi.org/legacy/'
